### ISSUE TITLE
Config Option Feature Request 

### ISSUE THREAD

**Issue by Darkosto** [GoryMoon/ViesCraftTweaker#2]
Hey Gory,

Can you look into a config option to universally allow all ViesCraft items/blocks to only be craftable in the Airship Workbench? I was looking to using that bench as the gate to VC, but I'd rather not have to remake every single recipe in the mod.

Thank you :)

**Comment by GoryMoon** [comment]
As of the 1.12 version of ViesCraft the Airship Workbench is a normal crafting table with the addition of showing the items on top and holding them when closed. There's not much I can do about it.

The recipes that is uses are the vanilla recipes and all items in ViesCraft have normal crafting recipes.
From it's changelog for 1.12:

> The Airship workbench works a little differently now. All airship recipes can be crafted in the standard Minecraft Crafting Table, and the Airship Workbench can craft all items that the Minecraft Crafting Table can! Main difference? The Airship workbench can store items!

Also this comment on it's curse page:
![Comment of crating table](https://i.imgur.com/zVG5IkU.png)

**Comment by Darkosto** [comment]
Yeah, I saw those messages but was still hoping something could be done. Thanks for the reply though!

**Comment by GoryMoon** [comment]
After thinking about it for a little while now there might be a way to make it work.

Will have to check and test some things.

**Comment by GoryMoon** [comment]
Nope, that idea don't work, the idea was to maybe cancel an event if it was vc items not in the airship workbench but there is no easy way of doing it as there is no event to do it atm, would need to add one to make it work.
